api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: 3000
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
  template:
    volumes:
      - name: grafana-bm0
        storageType: AzureFile
        storageName: {{ .Env.SERVICE_GRAFANA_VOLUME_BM0_NAME }} 
      - name: grafana-bm1
        storageType: AzureFile
        storageName: {{ .Env.SERVICE_GRAFANA_VOLUME_BM1_NAME }} 
    containers:
      - image: {{ .Image }}
        name: grafana
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: PROMETHEUS_ENDPOINT
            value: http://prometheus.internal.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
        volumeMounts:
          - volumeName: grafana-bm0
            mountPath: /etc/grafana
          - volumeName: grafana-bm1
            mountPath: /var/lib/grafana/dashboards
    scale:
      minReplicas: 1
tags:
  azd-service-name: grafana
  aspire-resource-name: grafana
