api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      additionalPortMappings:
        - targetPort: 4318
          external: false
      external: false
      targetPort: 4317
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
  template:
    volumes:
      - name: otelcollector-bm0
        storageType: AzureFile
        storageName: {{ .Env.SERVICE_OTELCOLLECTOR_VOLUME_BM0_NAME }} 
    containers:
      - image: {{ .Image }}
        name: otelcollector
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPIRE_API_KEY
            value: ""
          - name: ASPIRE_ENDPOINT
            value: https://localhost:21032
          - name: ASPIRE_INSECURE
            value: "false"
          - name: PROMETHEUS_ENDPOINT
            value: http://prometheus.internal.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}/api/v1/otlp
        volumeMounts:
          - volumeName: otelcollector-bm0
            mountPath: /etc/otelcol-contrib/config.yaml
    scale:
      minReplicas: 1
tags:
  azd-service-name: otelcollector
  aspire-resource-name: otelcollector
